# Site
name: "xvg5"
title: "xvg5"
description: "Build relationships, not links"
logo: '/favicon.ico'
favicon: '/favicon.ico'
baseurl: /
google_analytics: 'UA-246564983-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  admin:
    name: Rais Fazriansyah
    display_name: Rais Fazriansyah
    gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhFwGjE_3CniDpICGJCN6SFJs9AxE1E_O5P87qmdK5YLZ0RiGX9dvRbkLTEADd7gn1oyZDImcsnBlJvVo2qHmnx42x9tplw9HiMT-pTxEKN5_AfmO3gclpW2ARXyBb_dTR2iSqCt9qXK8dAxp9JvcOfhZ4-Fpv9PYgtfPubIiNp4mSKPpGKXF9TIFIs-HY/s1600/20241019_225029.jpg
    email: rfazriansyah376@gmail.com
    web: /aboutme
    description: "Author of this blog"
  admin2:
    name: Feni Putri Andini
    display_name: Feni Putri Andini
    gravatar: https://media.licdn.com/dms/image/v2/D5603AQEfKeD3q5ekTA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1728446307717?e=2147483647&v=beta&t=qyg8dR_DtRsuSBmbjV2E7aQwT17A1RqWy6O4WY2xELA
    email: rfazriansyah376@gmail.com
    web: https://www.linkedin.com/in/feni-putri-andini-64363b23b?trk=my-network_member-name
    description: "Social Media Specialist"
  admin3:
    name: Mila Salsabila
    display_name: Mila Salsabila
    gravatar: https://media.licdn.com/dms/image/v2/D5603AQGhB4bt-I8hMg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1673430303130?e=2147483647&v=beta&t=27dp2f3HHPPeGEiFGfAHYoRbrKmjLJ5L7x9iQsJdTew
    email: rfazriansyah376@gmail.com
    web: https://www.linkedin.com/in/mila-salsabila-072872261?trk=my-network_member-name
    description: "Content Creator , Media Social Specialist, Marketing & Sales"
  admin4:
    name: Annisa Mauliani
    display_name: Annisa Mauliani
    gravatar: https://media.licdn.com/dms/image/v2/C5603AQH9E_cf_BBpQA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1630396406257?e=2147483647&v=beta&t=lpLlvk490_pWJqZf0NJFk0bfdT6sAwCdnZoMVzqO4kE
    email: rfazriansyah376@gmail.com
    web: https://www.linkedin.com/in/annisa-mauliani?trk=feed-detail_main-feed-card_feed-actor-name
    description: "IT Project Manager"
  admin5:
    name: Hanifa Insyira
    display_name: Hanifa Insyira
    gravatar: https://media.licdn.com/dms/image/v2/D5603AQHzwb83yEr9vA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1702258055403?e=2147483647&v=beta&t=yjNaNclwj7mITm9pKsLyDFijDKhRUsTfoK0BJeIcQsE
    email: rfazriansyah376@gmail.com
    web: https://www.linkedin.com/in/hanifains?trk=people-also-viewed_member-name
    description: "Social Media Enthusiast, Public Relations, Content Creator"
  admin6:
    name: Anitawati Bachtiar
    display_name: Anitawati Bachtiar
    gravatar: https://media.licdn.com/dms/image/v2/C5103AQEGSnY5L-S-9w/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1573795533551?e=2147483647&v=beta&t=ttUNXhaH9DG6L8TFNvMspN-J-sFCHtvB7b7BtMbHJ54
    email: rfazriansyah376@gmail.com
    web: https://www.linkedin.com/in/anitawati-bachtiar-531880a7?trk=people-also-viewed_member-name
    description: "ENG-INA translator & interpreter"
  admin7:
    name: Nurul Hikmah A
    display_name: Nurul Hikmah A
    gravatar: https://media.licdn.com/dms/image/v2/D5603AQF1_XlqJhZZrg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1685318100390?e=2147483647&v=beta&t=f_s25kHG3hVSyWHUNYNVZTOLrCHfnIg9GM__2ZSdxX4
    email: rfazriansyah376@gmail.com
    web: https://www.linkedin.com/in/nurul-hikmah-a-a8456620b?trk=people-also-viewed_member-name
    description: "Freelance Writer"
  admin8:
    name: Ajizah
    display_name: Ajizah
    gravatar: https://media.licdn.com/dms/image/v2/C4E03AQGGzYE60z0poQ/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1636463492460?e=2147483647&v=beta&t=MPUEh7Wfqp58dlTFET9rodtbz_B1XBT2Va84EGITfWM
    email: rfazriansyah376@gmail.com
    web: https://www.linkedin.com/in/ajizah-638639216?trk=people-also-viewed_member-name
    description: "Freelance Web Development, Data Analyst"       
  admin9:
    name: Anggita Permata
    display_name: Anggita Permata
    gravatar: https://media.licdn.com/dms/image/v2/C5603AQEhXoJMkLqkCg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1629253980670?e=2147483647&v=beta&t=HD3FNM6q_nizS_uWoFmWGgXH0T6zJOOZZtn48ghMK4s
    email: rfazriansyah376@gmail.com
    web: https://www.linkedin.com/in/anggita-permata-431945182?trk=people-also-viewed_member-name
    description: "Content Writer"
  admin10:
    name: Fenny Laurenze
    display_name: Fenny Laurenze
    gravatar: https://media.licdn.com/dms/image/v2/D4E03AQFBgOn1kONTQw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1684341177559?e=2147483647&v=beta&t=pYxTsiA4qR_OKWaPHqt1zG-iOPwv_ZFDzMUua99wkcc
    email: rfazriansyah376@gmail.com
    web: https://www.linkedin.com/in/fenny-laurenze-9b0779272?trk=people-also-viewed_member-name
    description: "Sales & Marketing Specialist"
        
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '{{ site.url }}/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

